# Copyright (C) 2018 - 2020 MrYacha.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# This file is part of Sophie.


stages:
  - test
  - release


python:flake8:
  image: python:latest
  stage: test
  allow_failure: true
  before_script:
    - pip install flake8 pyflakes
    - pip install flake8-bugbear flake8-builtins flake8-print
  script:
    - cd /builds/SophieBot/sophie/
    - python3 -m flake8 sophie


python:mypy:
  image: python:latest
  stage: test
  allow_failure: true
  before_script:
    - pip install mypy
  script:
    - cd /builds/SophieBot/sophie
    - pip install -r requirements.txt
    - python3 -m mypy sophie


docker_branch:
  # Builds docker image with tag same as commited branch
  image: docker:latest
  stage: release
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"
  only:
    - stable
    - unstable
    - staging
    - v3


docker_latest:
  # Builds docker image with 'latest' tag
  image: docker:latest
  stage: release
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:latest"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"
  only:
    - stable

docker_version:
  # Builds docker image with version tags
  image: docker:latest
  stage: release
  services:
    - docker:dind
  before_script:
    - apk add python3
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - VERSION_FULL=$(python3 -c "import sophie.version as version; print(version.version)")
    - VERSION_PATHVERSION=$(echo $VERSION_FULL | sed 's/.*-//')
    - VERSION_MAJOR_MINOR=$(echo $VERSION_FULL | sed 's/-.*//')
    - VERSION_MAJOR=$(echo $VERSION_MAJOR | sed 's/\..*//')
    - TAGS="$VERSION_FULL $VERSION_MAJOR_MINOR $VERSION_MAJOR"

    - for tag in $TAGS; do
        DOCKER_IMAGE="$CI_REGISTRY_IMAGE:$tag";
        docker build -t "$DOCKER_IMAGE" .;
        docker push "$DOCKER_IMAGE";
      done
  only:
    - stable
    - unstable
    - staging
    - v3
